<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_type_user</name>
   <tag></tag>
   <elementGuidId>57fb5326-1be5-4ccd-8927-c3934b1876c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='type_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#formAddNewInvitation #type_user</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>86cb14d9-cd32-412f-aa95-e726daa9b128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type_user</value>
      <webElementGuid>49d939cb-06a4-4efe-985a-a4c56b514df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>d4598f50-9b78-418f-a95c-63cf16c2ae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type_user</value>
      <webElementGuid>4edb87db-ca46-4201-b848-1e9d85ac91d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                    VVIP
                                                                                                    VIP
                                                                                                    Internal
                                                                                                    Regular
                                                                                                    Panitia
                                                                                                </value>
      <webElementGuid>93935a4a-f11c-4bbb-9d0c-e6d01f580623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAddNewInvitation&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-12&quot;]/select[@id=&quot;type_user&quot;]</value>
      <webElementGuid>a420d013-8f3c-4b05-8c79-c3d32316450f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='type_user']</value>
      <webElementGuid>7e86906c-1b4f-44db-b590-8c5930ec5707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddNewInvitation']/div/div[2]/div/div/div[8]/div/select</value>
      <webElementGuid>0e1cee03-f37c-4b95-a12d-6bf5a149284b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Add Invitation'])[1]/following::select[2]</value>
      <webElementGuid>a166dd02-b4ba-4e64-a3d0-b0dd4ebf1e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 89 entries'])[1]/following::select[2]</value>
      <webElementGuid>94790ff0-0f20-40d7-9e00-0a65e160141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[2]</value>
      <webElementGuid>8248236d-56f8-479e-8803-5922cbc752f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Edit Invitation'])[1]/preceding::select[2]</value>
      <webElementGuid>bf6f0ec1-d19f-4e6a-8c85-05e93425a5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>d4d1f4dc-8f12-4275-ba4f-ab5e264ecab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'type_user' and @name = 'type_user' and (text() = '
                                                                                                    VVIP
                                                                                                    VIP
                                                                                                    Internal
                                                                                                    Regular
                                                                                                    Panitia
                                                                                                ' or . = '
                                                                                                    VVIP
                                                                                                    VIP
                                                                                                    Internal
                                                                                                    Regular
                                                                                                    Panitia
                                                                                                ')]</value>
      <webElementGuid>d19cb3eb-0564-40a0-992e-7c74eeb196a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
