<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_New-Map-Menu</name>
   <tag></tag>
   <elementGuidId>57327621-5ac2-4760-ad3e-0725c2065e3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content2 > div.card-header.py-3 > #newData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='newData'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddfdf6c8-6cd3-4877-8a6d-1b342f174760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newData</value>
      <webElementGuid>c395e90d-2049-4811-874a-c1e43e8e2746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>947c3db7-c56a-4197-8589-9bdcb1d3af79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3ba43662-00ff-451a-a08b-32f92444643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal_Add_map_menu</value>
      <webElementGuid>1a4f1670-1f98-4317-8b1a-17c086d3ee04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  New</value>
      <webElementGuid>6c4539fd-d384-4957-8433-c30a15fb925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content2&quot;)/div[@class=&quot;card-header py-3&quot;]/button[@id=&quot;newData&quot;]</value>
      <webElementGuid>a301f14d-f19b-4861-9387-5b6eef4a418f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='newData'])[2]</value>
      <webElementGuid>d3dc5cde-c09c-4ba6-8d97-d352fd75d9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content2']/div/button</value>
      <webElementGuid>24f5e717-0a4f-48a7-af05-980c12d79bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 6 of 6 entries'])[1]/following::button[1]</value>
      <webElementGuid>b27c6ad7-1210-48c1-ab8a-ee9992867839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[6]/following::button[3]</value>
      <webElementGuid>b8ddc26c-ede6-4e7f-ae2a-cf83dc67f4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Roles'])[2]/preceding::button[1]</value>
      <webElementGuid>25823c6e-ab67-47bf-a576-3a677f472442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button</value>
      <webElementGuid>ead2f63c-6307-4996-9667-2098ebeae17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'newData' and (text() = '  New' or . = '  New')]</value>
      <webElementGuid>0d082188-cb0f-46a6-96ea-aeffe022ae08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
