<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Delete</name>
   <tag></tag>
   <elementGuidId>bb15ef98-acfe-4d1f-b2cc-37d427828530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_delete_roles']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;superadmin Active  &quot;i] >> #btn_delete_roles</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ac6aa586-ab35-4a4c-a7b0-05df5c35d07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash</value>
      <webElementGuid>ce2f3a40-50f9-4713-89bf-bf9082004dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtRolesData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]/button[@id=&quot;btn_delete_roles&quot;]/i[@class=&quot;fa fa-trash&quot;]</value>
      <webElementGuid>4f706b61-d6f3-4553-a3aa-6622a09463be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn_delete_roles']/i</value>
      <webElementGuid>c991461b-9e66-40f4-887b-7ec961567ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>61b5605f-dd72-45f2-a282-192630923809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
