<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Showing_Next</name>
   <tag></tag>
   <elementGuidId>09ca78e1-27a1-4798-b606-15171fe18cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtRolesData_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dtRolesData_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dtRolesData_next</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87ae3b9a-6cf4-4061-95d5-7d19cc4088ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>fc12175a-efb2-44ee-8411-b0cc1d289f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtRolesData_next</value>
      <webElementGuid>c5e5fb1f-f770-4af5-9985-a0bb42adbcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>81cf402e-0781-4aca-901d-83619cb166a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtRolesData_next&quot;)</value>
      <webElementGuid>38a0b60a-0db0-414e-9977-1d440c6928c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dtRolesData_next']</value>
      <webElementGuid>04ce8b23-5910-4953-a005-48e2d358b7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtRolesData_paginate']/ul/li[3]</value>
      <webElementGuid>652e8329-8155-432f-a354-2e3264917ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 6 of 6 entries'])[1]/following::li[3]</value>
      <webElementGuid>b358f953-ac14-41a0-aaca-8fd1f0bd3fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[6]/following::li[3]</value>
      <webElementGuid>2fe667b6-cb74-41d2-8814-e5957d856793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/preceding::li[1]</value>
      <webElementGuid>6271283f-a4bc-4127-acca-adae41ca2fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Roles'])[2]/preceding::li[1]</value>
      <webElementGuid>447c996d-c67a-4c32-bd2b-35cea28675c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]</value>
      <webElementGuid>a57641f4-c140-4446-8e92-6d5d054ac5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dtRolesData_next' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>edd19c8a-63ee-4932-8c87-b46e20ea82c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
