<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkboxes_Invitation</name>
   <tag></tag>
   <elementGuidId>e456f736-023c-4fad-8b3d-7832b4b66bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.dt-checkboxes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='42']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;6acfe4dd1e Link 2702558342 guest-8-4 guest8_4@example.com +6289557242838 Company Bus 8 Internal G Available   &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a9672c2-398e-45e3-b860-9a5af54dbce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4150551e-7bc0-45b8-b86f-a58aeec293fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>600d7ebd-2ac9-4f9b-a225-661cf5e459b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>a88ed0d1-0ecb-4f58-af4d-787294b908ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtInvitationData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-center dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>6bd5f4fa-28eb-4c49-898a-f442c5254b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='42']</value>
      <webElementGuid>400234cd-d307-4605-8589-0ec3bf7155fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtInvitationData']/tbody/tr/td/input</value>
      <webElementGuid>43ce72a8-8c66-4f54-8315-18cce0608e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>18ae24c2-340f-4a51-828f-9a94180d3313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>973af1e2-9cea-4d73-9fc6-8deb55a9dccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
