<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scan-Barcode</name>
   <tag></tag>
   <elementGuidId>f83a9b8c-82e5-45a9-84f8-7e6e42a7d495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qr-shaded-region</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qr-shaded-region']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#qr-shaded-region</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9564b559-12dc-4f8c-a169-66b24ed5971c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qr-shaded-region</value>
      <webElementGuid>8d1396ad-fd8c-424e-a321-acf021de3840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qr-shaded-region&quot;)</value>
      <webElementGuid>0c82430a-8181-4b86-8018-16420f4a3578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='qr-shaded-region']</value>
      <webElementGuid>124dd91b-24ef-4100-95bd-1b615e60dec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qr-reader']/div</value>
      <webElementGuid>e2977278-4da8-4776-8186-84fd5a91898d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='👥 Guest List'])[1]/following::div[6]</value>
      <webElementGuid>5aa402d5-5417-45c7-b30c-4c11d742340e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📷 Scan'])[1]/following::div[6]</value>
      <webElementGuid>1fce3f17-c7ca-4c16-9a5d-c60e763a5efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scanner paused'])[1]/preceding::div[9]</value>
      <webElementGuid>f1370b23-4d86-4506-ab83-97a24ce761b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='entries per page'])[1]/preceding::div[15]</value>
      <webElementGuid>d6059208-ac27-4969-b5ae-e8f7a5bcde5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/div</value>
      <webElementGuid>f2655912-8b5c-4cbf-a7ff-d755f9077c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'qr-shaded-region']</value>
      <webElementGuid>f56feffe-f0ab-4ef7-85a0-498609afa4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
