<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Bus-Number</name>
   <tag></tag>
   <elementGuidId>8003ffc8-4888-477f-9abc-3b72ec61b037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bus_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bus_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bus No&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d8709c4-5ebe-494a-b322-6718a2eb2333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bus_no</value>
      <webElementGuid>da5abcaa-27b4-4e42-954c-58833dc475d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>900e2787-6ea4-4074-b0b4-6d07d6ab038a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Bus --No BusABCDEFGHIJKLMNOX</value>
      <webElementGuid>17a3aec8-8543-4241-879d-ee3d74bbecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bus_no&quot;)</value>
      <webElementGuid>7efe960b-4c5b-4bef-9c2d-19d5a88319ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bus_no']</value>
      <webElementGuid>61b48ea1-0734-4250-aaa4-85c642eff7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bus No'])[1]/following::select[1]</value>
      <webElementGuid>911f9082-444d-4d65-8fa9-bbdcf07226ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::select[2]</value>
      <webElementGuid>0e5ad9a4-934a-4f88-8be6-cfeefd533766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📷 Scan'])[1]/preceding::select[1]</value>
      <webElementGuid>715ee77f-bb7b-42b7-82d0-f7efa3dfe18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='👥 Guest List'])[1]/preceding::select[1]</value>
      <webElementGuid>fb9b2820-2e75-4981-8677-1b4f7aaa5d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>c5759b32-51b1-44e2-b347-a7b534b1a1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'bus_no' and (text() = '-- Pilih Bus --No BusABCDEFGHIJKLMNOX' or . = '-- Pilih Bus --No BusABCDEFGHIJKLMNOX')]</value>
      <webElementGuid>0189b9bf-ad5a-4f5b-b32e-49dc9743c62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
