<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>c8c0d473-7040-4f93-bdb8-26a3369ecc36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codedp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codedp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>daa7907f-834a-4851-9862-f2e9ff10c64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2cc075e4-e19d-443d-853b-af14cb62c3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>2fac530b-e26d-4cf5-878b-51addbf7cb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codedp</value>
      <webElementGuid>10359700-7358-48ee-814f-edf9f5c36f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codedp</value>
      <webElementGuid>e9a7a5fa-c68e-4531-bdde-4af57ee691c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>ce8057a6-b541-483f-95ce-f2a388f7fefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAdd&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-12&quot;]/input[@id=&quot;codedp&quot;]</value>
      <webElementGuid>679d24a9-56ed-481b-b21d-5620481b5d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codedp']</value>
      <webElementGuid>9b304642-bfc3-4064-ab55-f33eb7092150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e33cc649-f2ba-4cdb-af1d-37f67267a03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>51e1741b-e244-41e3-8f26-23761e4722ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'codedp' and @id = 'codedp' and @placeholder = 'Code']</value>
      <webElementGuid>77e82215-767a-434d-81a3-f1925c301229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
