<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_IND</name>
   <tag></tag>
   <elementGuidId>9b891c69-decd-4e57-9a26-d134b04c1174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.lang-btn.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;setLanguage('id')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;IND&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14071c8c-45c8-46cc-9831-4ec43b6aaa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lang-btn active</value>
      <webElementGuid>d27f904e-c20e-4c58-8d30-980e2bd50867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setLanguage('id')</value>
      <webElementGuid>96fe1e4b-f8bc-4684-a41e-5d67d4eae3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IND</value>
      <webElementGuid>4dae1ad7-e0f5-45b0-aba1-52792972d2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;form-container&quot;]/div[@class=&quot;lang-toggle&quot;]/button[@class=&quot;lang-btn active&quot;]</value>
      <webElementGuid>35017d97-7740-44aa-a585-3bd7ba5ba842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;setLanguage('id')&quot;]</value>
      <webElementGuid>ecc3381a-2839-44ee-9450-43de07391fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENG'])[1]/preceding::button[1]</value>
      <webElementGuid>9988f05c-b386-49fe-848b-e82788e7e4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penilaian Performance Gala Dinner'])[1]/preceding::button[2]</value>
      <webElementGuid>45869b62-ecee-401a-ad93-943e8b7437e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IND']/parent::*</value>
      <webElementGuid>d50da185-4528-4553-b34f-f31a8a6eab39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5e9019b5-1136-4610-b38b-7849e3afaddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'IND' or . = 'IND')]</value>
      <webElementGuid>6ef417fa-04bd-437a-92f8-6e5a18f1eaa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
