<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_6_Engagement</name>
   <tag></tag>
   <elementGuidId>ddc1998d-e7c4-455c-a761-14ef2d5c628b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='★'])[35]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(8) > .stars > span:nth-child(6)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2be7cd3d-64a3-4c01-b5d8-5187d2be36b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star</value>
      <webElementGuid>b7ebd56d-2fbc-4459-ba1c-82ac0e8dec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>7c9bb82a-21a6-46ae-8c93-5f352ac4c6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>★</value>
      <webElementGuid>6f4ae23b-79b6-4bc6-bbe5-8b5f54170e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;sf-js-enabled&quot;]/body[1]/div[@class=&quot;form-container&quot;]/div[@class=&quot;question&quot;]/div[@class=&quot;stars&quot;]/span[@class=&quot;star&quot;]</value>
      <webElementGuid>fa601cdb-2c0a-48bf-b88e-5d5c56cab3b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='★'])[35]/following::span[1]</value>
      <webElementGuid>3ebebd79-a5b4-4d9f-bb7f-01491b26da9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='★'])[34]/following::span[2]</value>
      <webElementGuid>cd4d7bf4-8bb5-4568-8205-0604136651b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='★'])[37]/preceding::span[1]</value>
      <webElementGuid>5f81106b-d874-42bb-813b-938477c02123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='★'])[38]/preceding::span[2]</value>
      <webElementGuid>23be8308-6ae2-4b9b-a468-127875d5419c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/span[6]</value>
      <webElementGuid>ccbd2871-a598-4798-919a-bfe9a850a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '★' or . = '★')]</value>
      <webElementGuid>ec6fc317-0bac-45cc-bb72-4e2d68b291fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
