<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roles</name>
   <tag></tag>
   <elementGuidId>45e0434d-5ae9-402d-83a2-a680a8a0c73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#roles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='roles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Roles&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>694b96a2-5de7-46d3-b33d-4cd140eb1bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d68c4d71-8e25-436e-941b-afda4fe4f314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>be7cd7f7-59b5-491a-a743-0b240071428a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roles</value>
      <webElementGuid>84d75b43-c123-4d94-9784-ec88480d83f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>roles</value>
      <webElementGuid>2ee72e4d-d329-406c-80b1-d0eb9b73f545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Roles</value>
      <webElementGuid>c0f58553-f269-46af-814b-19ec0958f015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>30fafc28-4fad-4b31-bfe5-386e46e4f71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roles&quot;)</value>
      <webElementGuid>e002d7d6-67d8-4f35-ae9e-a5dc083b159c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='roles']</value>
      <webElementGuid>36eba025-30af-4716-b8c0-70190dc705ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddNewRoles']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>10540158-e801-4623-bbf1-6fdbf915ffa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/input</value>
      <webElementGuid>dde83afa-d19a-43df-889d-858b28f042ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'roles' and @id = 'roles' and @placeholder = 'Roles']</value>
      <webElementGuid>a78d7460-25c5-4e98-9947-0e2fb84bd36d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
