<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Showing_Back</name>
   <tag></tag>
   <elementGuidId>4f8b1c6e-2c7a-43a6-b9d0-b3954f093f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtPotential_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dtPotential_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dtPotential_previous</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e7d9f52e-691b-4ffc-af84-dafd7b0b4f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>65c49bbf-3468-4ca8-a654-85e44d8da1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtPotential_previous</value>
      <webElementGuid>bd84513f-e09f-44a5-a347-d2c3ee517ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>e282ebc2-3309-4adb-ad36-5c373aaac892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtPotential_previous&quot;)</value>
      <webElementGuid>5fabb7bb-d49d-4d80-a5d1-797dd462c96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dtPotential_previous']</value>
      <webElementGuid>4a58991c-76c2-4bdf-802c-16052f12aefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtPotential_paginate']/ul/li</value>
      <webElementGuid>e14c4ee5-8e0c-4c23-b60c-c585cf0ce0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 77 entries'])[1]/following::li[1]</value>
      <webElementGuid>ff594dab-c8ad-41e2-9449-6805d6b09fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Bus 10'])[1]/following::li[1]</value>
      <webElementGuid>6418f33d-3933-454c-add5-e30ebff32b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © galadinner.mmsgroup.co.id 2023'])[1]/preceding::li[9]</value>
      <webElementGuid>490e163d-75ae-478d-9c99-00cc7ff09abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready to Leave?'])[1]/preceding::li[9]</value>
      <webElementGuid>4003f5e5-1f69-4c25-b18f-2d6924ac64c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>7b5841ff-40ae-49f7-8f90-51926d4e28b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dtPotential_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>a5a8a0d8-bfd4-46bd-ac38-0f4e7390ce83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
