<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Showentries_List-Potential</name>
   <tag></tag>
   <elementGuidId>64814b11-f77b-46ab-959d-4f66e9fa5764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;dtPotential_length&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='dtPotential_length']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show 102550100 entries&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c5f29062-9f6b-4091-878e-c3dfb65ee5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dtPotential_length</value>
      <webElementGuid>9ace3077-2610-44b3-8161-17ff9933fe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dtPotential</value>
      <webElementGuid>2fa82886-0ff7-4c21-91dc-3cae905c0dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select custom-select-sm form-control form-control-sm</value>
      <webElementGuid>f6174040-571b-40af-853a-f51339cd192a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>c7fffc75-3524-4460-84c5-85482bf3eb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtPotential_length&quot;)/label[1]/select[@class=&quot;custom-select custom-select-sm form-control form-control-sm&quot;]</value>
      <webElementGuid>aea64c9b-56c7-4dbd-a56e-c4e9b6a3be7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='dtPotential_length']</value>
      <webElementGuid>f8bc1b7a-6f6a-452d-bee8-43072680b215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtPotential_length']/label/select</value>
      <webElementGuid>a7bc94b2-5245-41da-8858-509fd0224fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potential Data'])[1]/following::select[1]</value>
      <webElementGuid>2af9c883-7a82-4d65-828c-0f0dd2efa472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[1]</value>
      <webElementGuid>8250322e-4d38-4edf-9442-448a87a7df71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[1]/preceding::select[1]</value>
      <webElementGuid>b178e394-ec52-4ea5-b93d-08487b38b5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>14c6d7fc-c685-49b0-8929-33bc053ab451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dtPotential_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>6e0e4211-ad9f-48e1-a306-a44b758fe516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
