<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete_Data-Invitation</name>
   <tag></tag>
   <elementGuidId>688daeb2-d36d-46bb-918d-c45135845367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_delete_inv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_delete_inv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;6acfe4dd1e Link 2702558342 guest-8-4 guest8_4@example.com +6289557242838 Company Bus 8 Internal G Available   &quot;i] >> #btn_delete_inv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5dee03e-1201-4a36-96c3-3464b9a2dbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_delete_inv</value>
      <webElementGuid>cf284f86-0b9c-4396-b4eb-41b34e3d186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>d0d4c74a-2b94-4368-8913-ea08eae8798d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtInvitationData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[12]/button[@id=&quot;btn_delete_inv&quot;]</value>
      <webElementGuid>6aa55592-c209-4e2b-a307-6bd2b003933e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_delete_inv']</value>
      <webElementGuid>4792eba3-e9d1-4b53-80c9-8a5e82e05134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtInvitationData']/tbody/tr/td[12]/button[3]</value>
      <webElementGuid>af071fe6-38d9-45ca-961f-5c7822d4a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::button[3]</value>
      <webElementGuid>f30affc5-6e56-4dcf-abb0-f36349d6b512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::button[3]</value>
      <webElementGuid>5463e3a1-3a2e-4d8a-a58e-2c49efe457b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[3]/preceding::button[1]</value>
      <webElementGuid>ba980218-1c64-4c2d-b6be-b504dac272ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firman'])[1]/preceding::button[1]</value>
      <webElementGuid>90fff070-3c98-4536-ab76-8d76bd9ddde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>2f2e15cb-7024-4f31-8671-a5e1bdd530d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_delete_inv']</value>
      <webElementGuid>fced9289-cbb2-4d5a-86d2-0945cefc705f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
