<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit-Data-Invitation</name>
   <tag></tag>
   <elementGuidId>42243ad9-f335-447a-9857-4c61f3b4d98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_edit_inv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_edit_inv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;6acfe4dd1e Link 2702558342 guest-8-4 guest8_4@example.com +6289557242838 Company Bus 8 Internal G Available   &quot;i] >> internal:attr=[title=&quot;Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7cb1e91-76c5-4085-a5ed-5d51937d2759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_edit_inv</value>
      <webElementGuid>2494a8c5-1a57-4052-a91e-de749de2f229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>3c2a96da-1f0c-4859-8971-ffb420142373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>c8e39383-e867-49a7-93e3-4245353476f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtInvitationData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[12]/button[@id=&quot;btn_edit_inv&quot;]</value>
      <webElementGuid>5969c1c2-af9e-48e5-b1ea-11510e3a6f4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_edit_inv']</value>
      <webElementGuid>bcbedbe6-e48f-45e8-8ae8-d0b273e26c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtInvitationData']/tbody/tr/td[12]/button[2]</value>
      <webElementGuid>9f881f99-a2e1-4946-924a-8d07f815ca1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::button[2]</value>
      <webElementGuid>69faac31-3a94-4680-8820-1f55e0a693f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::button[2]</value>
      <webElementGuid>f93334a2-09fc-42f0-8414-09e78e93e8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[3]/preceding::button[2]</value>
      <webElementGuid>9a97efa5-5054-4b09-a973-e8a8e42a2086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firman'])[1]/preceding::button[2]</value>
      <webElementGuid>763376fa-6c6b-499f-a495-e9110fd12264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/button[2]</value>
      <webElementGuid>a4e0067f-4116-4f4b-8529-0804c68abb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_edit_inv' and @title = 'Edit']</value>
      <webElementGuid>9b186e29-7b5b-4711-8220-6d95df458e38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
