<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status_Edit</name>
   <tag></tag>
   <elementGuidId>14e42cd7-ea6d-40ae-b56b-3bbc629f473d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='status'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formEdit > div.modal-content > div.modal-body > div > div > div.form-group.row > div.col-sm-6 > #status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#formEdit #status</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>96b88b12-a130-4f03-b3c9-2eea7635468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>d40427d7-b96f-4307-b5c2-bfd2b78df692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>6b081138-a523-42ec-bde4-1c2a31295a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>5a52b449-b2b0-485f-bb09-f7a494499929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Active
                                                    Inactive
                                                </value>
      <webElementGuid>ff51826c-a55f-4bf4-8623-5afe4821e071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEdit&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@id=&quot;status&quot;]</value>
      <webElementGuid>c0238a7d-1115-4431-a14b-92443e63b87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='status'])[2]</value>
      <webElementGuid>85fc1f5b-8dd1-4c21-b274-49e28e94d394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEdit']/div/div[2]/div/div/div[2]/div[2]/select</value>
      <webElementGuid>f6401560-69db-4f3c-b135-264647c53043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/following::select[1]</value>
      <webElementGuid>eada1b47-308c-4b58-8c22-143b91dd0780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='is Bus'])[2]/following::select[2]</value>
      <webElementGuid>a5b82a58-cc1d-4333-9fe2-537006291350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[3]/preceding::select[1]</value>
      <webElementGuid>93d5d117-5c5d-4f9b-b4a8-98e2391f85db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::select[1]</value>
      <webElementGuid>a447f8a6-b110-467b-b048-035ff13b2980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/div[2]/div/div/div[2]/div[2]/select</value>
      <webElementGuid>6dad846b-67e7-4b70-96cd-3ed21d9c15ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'status' and @name = 'status' and (text() = '
                                                    Active
                                                    Inactive
                                                ' or . = '
                                                    Active
                                                    Inactive
                                                ')]</value>
      <webElementGuid>367ee17f-db40-4102-b272-17940d103bde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
