<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Commit_Jameson</name>
   <tag></tag>
   <elementGuidId>6e1f367d-7d45-452f-9c50-9ff3fa702efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-commit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-commit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Commit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64287342-76d5-4a41-9833-26215337d9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3041b1e7-81ac-47e0-88f4-e16182982220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>15951022-0a68-48ce-9043-f90b795bc8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-commit</value>
      <webElementGuid>f3284db5-da88-4e76-af54-261d71d99460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commit</value>
      <webElementGuid>34667381-cc12-46f0-9373-d729cb34984e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-commit&quot;)</value>
      <webElementGuid>ce2a1d07-1803-4088-8ace-1d4b794494ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-commit']</value>
      <webElementGuid>e8bde93e-3043-4246-8d5d-9a573252b2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-example-navbar-collapse-1']/div[2]/button</value>
      <webElementGuid>49c2c800-03b1-4675-8062-21be40d128a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold 50 Gram'])[1]/following::button[1]</value>
      <webElementGuid>92aafb12-b0d8-49c9-9cb8-dcecfaefa126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gold 1 gr'])[1]/following::button[1]</value>
      <webElementGuid>38635ac8-df43-487b-8a91-460af1e2be5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Spin!'])[1]/preceding::button[1]</value>
      <webElementGuid>409aa79a-9c1b-4126-abab-a204eb9b6e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAMESON BLACK BARREL'])[2]/preceding::button[2]</value>
      <webElementGuid>96ee86d1-3f41-4bcb-a6bc-21f4c652183b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Commit']/parent::*</value>
      <webElementGuid>3299507b-fd67-44b9-8683-fd1c4ca699a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>a27029a4-7d13-45e4-9b9f-2c87fc0b73ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-commit' and (text() = 'Commit' or . = 'Commit')]</value>
      <webElementGuid>5cfd3df4-0e76-42b9-9b47-41e3c9d7ef2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
