<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_delete_email</name>
   <tag></tag>
   <elementGuidId>7d594324-95ab-4df1-8a8c-a29857a5804c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;test@mail.com email_send_barcode {\&quot;receiver_name\&quot;:\&quot; Test\&quot;,\&quot;title\&quot;:\&quot;Mail from galadinner@mmsgroup.co.id\&quot;,\&quot;panel\&quot;:\&quot;success\&quot;,\&quot;barcode\&quot;:\&quot;0f29156d-4c8b-43f8-aad1-f43b39ab9839\&quot;,\&quot;url_barcode\&quot;:\&quot;https:\\/\\/dev-gathering.mmsgroup.co.id\\/\\/storage\\/qrcode\\/0f29156d-4c8b-43f8-aad1-f43b39ab9839.png\&quot;} &quot;i] >> internal:attr=[title=&quot;Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3b5fd50-8551-4506-975d-9e924cded927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_delete</value>
      <webElementGuid>6054547b-e96d-4726-94dc-c821ea212aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>1c0bceeb-908d-4d21-8234-22b059402230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>7a2a0acc-bd4f-466f-808a-ee7708f88782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtEmailQueueData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-center&quot;]/button[@id=&quot;btn_delete&quot;]</value>
      <webElementGuid>dc830d48-804c-45ea-95ef-285e7e76e7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_delete']</value>
      <webElementGuid>c6f0e20d-9b04-465f-9412-9723409d8caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtEmailQueueData']/tbody/tr/td[4]/button</value>
      <webElementGuid>1f57c54e-5440-4ee8-974c-2fa25bdc9421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='email_send_barcode'])[1]/following::button[1]</value>
      <webElementGuid>5a4b295d-1eac-4745-bf4d-84532c606418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test@mail.com'])[1]/following::button[1]</value>
      <webElementGuid>e35e24cf-d3bb-4bda-bcf5-b73f30a6da92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manto.manto@mmsgroup.co.id'])[1]/preceding::button[1]</value>
      <webElementGuid>00cabdc2-d075-4b6e-9457-3f8e1e5380d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='email_send_barcode'])[2]/preceding::button[1]</value>
      <webElementGuid>c6c600e9-f117-4ed5-9b8c-f62cbdfcbec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>7a845811-b060-4ba2-989c-c44093e74968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_delete' and @title = 'Edit']</value>
      <webElementGuid>6a3917be-42ec-41e5-8020-0a3c191bd60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
