<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Showing_Next</name>
   <tag></tag>
   <elementGuidId>70932ec5-f5a8-45f4-9f50-3ebb1da30b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtLogsEmailQueueData_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dtLogsEmailQueueData_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dtLogsEmailQueueData_next</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>de663475-477b-4e39-8dd6-1f350f8d05e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>be5b2559-ab98-48b1-9337-dbc937d2fbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtLogsEmailQueueData_next</value>
      <webElementGuid>ec0bf30f-7c20-4818-919d-bbaae680afc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>1ca76b17-d749-47f0-af9c-96f68e899d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtLogsEmailQueueData_next&quot;)</value>
      <webElementGuid>3d13586e-6abc-401d-b0b2-eacdcffd1e77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dtLogsEmailQueueData_next']</value>
      <webElementGuid>9ad243f9-9122-4674-b4e2-3fa0ca6fd526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtLogsEmailQueueData_paginate']/ul/li[2]</value>
      <webElementGuid>7e8b6d7e-9fe4-48ce-894c-1841d9fb7530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0 entries'])[1]/following::li[2]</value>
      <webElementGuid>f38a1731-239e-4d3c-b33b-fbf1d822d70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available in table'])[1]/following::li[2]</value>
      <webElementGuid>19611d37-926e-47a1-a0cd-0730bb12b173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Add Invitation'])[1]/preceding::li[1]</value>
      <webElementGuid>ec415cb7-8dcf-4ed6-aacb-6b0584f6cf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li[2]</value>
      <webElementGuid>ba5adabd-3103-43e3-ac95-0c359efbed9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dtLogsEmailQueueData_next' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>4821e231-02b4-40f4-a706-88c332a1a160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
