<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Showing-Back</name>
   <tag></tag>
   <elementGuidId>1a7d6dc8-89bb-4748-b037-dc5735d72501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtLogsEmailQueueData_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dtLogsEmailQueueData_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dtLogsEmailQueueData_previous</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>98b5ec33-b92b-48d6-8421-83c28adc09c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>5c38a43c-80a5-4a5d-acf6-e0f63c72a695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtLogsEmailQueueData_previous</value>
      <webElementGuid>8a7ecf60-da1e-4b1c-a900-e7f72f580e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>dd785296-5f4a-4fa3-9c78-7472571501b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtLogsEmailQueueData_previous&quot;)</value>
      <webElementGuid>f4ab926a-4197-409b-873e-918eee0bfe34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dtLogsEmailQueueData_previous']</value>
      <webElementGuid>e45fe9bd-4c9e-4978-9754-0856e1c6bf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtLogsEmailQueueData_paginate']/ul/li</value>
      <webElementGuid>f9d7f7ed-5d07-49e1-9685-ab0736e232a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0 entries'])[1]/following::li[1]</value>
      <webElementGuid>5f96226d-5d02-4423-9620-e50c01f68f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available in table'])[1]/following::li[1]</value>
      <webElementGuid>43438ee7-1320-4797-a13a-792ba8f36d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Add Invitation'])[1]/preceding::li[2]</value>
      <webElementGuid>900dd930-fc80-4397-ae7e-e382cfd40f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li</value>
      <webElementGuid>5df42898-9ab9-4ce4-8f00-d2bf3c2f500b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dtLogsEmailQueueData_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>29991be8-665a-47ff-a2bd-ddcd9ece9f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
