<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Configuration_updateConfig</name>
   <tag></tag>
   <elementGuidId>5cc4013a-3489-4256-9b26-876e8b791e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#updateConfig</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='updateConfig']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Update Config&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f334143c-08f2-480e-a2e1-6b82bb3093bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updateConfig</value>
      <webElementGuid>d08b2709-2e3d-4388-ae5d-b40f4da0f28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>2c62f00d-4a88-43d9-a7b3-d80b4840d3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>updateConfig()</value>
      <webElementGuid>134bcb24-1d3c-499c-830e-33512b59a191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Update Config
                            </value>
      <webElementGuid>0a815239-f1fc-4367-a5e6-3acba2a4c046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updateConfig&quot;)</value>
      <webElementGuid>02d3a402-f7b5-41ce-86df-c62a7a38f40c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='updateConfig']</value>
      <webElementGuid>e00e923f-1021-4a68-ba01-7962fa88b457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/button</value>
      <webElementGuid>f830523b-6ee5-4a8b-86a1-badd93030d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[2]/following::button[1]</value>
      <webElementGuid>9d188de3-900b-40a2-af15-8bf1843cf2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::button[1]</value>
      <webElementGuid>75d88a4f-017f-4bd4-b684-768bc62d2636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::button[1]</value>
      <webElementGuid>efdebcf2-bc75-410c-ba81-78ca25c67f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='interval_countdown'])[1]/preceding::button[1]</value>
      <webElementGuid>955c672c-943c-4df8-bfba-374c4fd3b0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update Config']/parent::*</value>
      <webElementGuid>fba12cd0-5936-4c7f-a634-6b5b15452938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>f8b7d8d4-ef0a-41d8-8f1f-522227e9b278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'updateConfig' and (text() = '
                                 Update Config
                            ' or . = '
                                 Update Config
                            ')]</value>
      <webElementGuid>5a4adb83-5c98-408e-8713-a577847ed147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
