<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Showing_Back</name>
   <tag></tag>
   <elementGuidId>db144151-8dbc-437c-a24b-30b7a6222ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtInvitationData_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dtInvitationData_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dtInvitationData_previous</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dbabeb72-bbf2-4609-a3e7-5f4fe63d0496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>03660b02-56b6-4616-ba3f-fdf1fa929d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtInvitationData_previous</value>
      <webElementGuid>f7fb96bb-6fc8-47ba-93a9-3bede3132007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>cb411f25-9b38-422a-8a9a-1b49b8189829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtInvitationData_previous&quot;)</value>
      <webElementGuid>2bf783ae-989b-412d-b504-3f966fbe155a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dtInvitationData_previous']</value>
      <webElementGuid>33176f83-bb8c-48c8-b95c-36776065115b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtInvitationData_paginate']/ul/li</value>
      <webElementGuid>a13b5bbb-3b70-4972-a6a3-27a1e5a91193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 88 entries'])[1]/following::li[1]</value>
      <webElementGuid>e3dc9ece-86b9-4f6c-a02f-6ccbdfc897d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eligible'])[7]/following::li[1]</value>
      <webElementGuid>ae5b36f8-7d5d-4655-8bdd-42819e1e818a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © galadinner.mmsgroup.co.id 2023'])[1]/preceding::li[9]</value>
      <webElementGuid>0b6c203b-023c-424e-b04b-f932809b1d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li</value>
      <webElementGuid>8117a29c-32a6-4fdb-87f6-a5b88aa521be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dtInvitationData_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>d108af7c-7224-4a62-94d3-4527638b1e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
