<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_New_Menu</name>
   <tag></tag>
   <elementGuidId>4f0227f8-2d3a-4737-b0b5-98aed208f3ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content3 > div.card-header.py-3 > #newData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='newData'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0af76ca8-0c7e-460c-a253-69e1815fa33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newData</value>
      <webElementGuid>0271e4e7-c9fd-4a53-9517-66477dd75495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>c75af7ec-837c-44e2-babb-a4d96f436f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0fb9f397-fe6c-483e-be04-bbf241d982fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal_Add_menu</value>
      <webElementGuid>aa9adab7-d3d2-4dc2-82a2-2ee8590224e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  New</value>
      <webElementGuid>94d7201a-a7b1-4d3e-8a7f-6e48c97b8a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content3&quot;)/div[@class=&quot;card-header py-3&quot;]/button[@id=&quot;newData&quot;]</value>
      <webElementGuid>2c504f2b-7be1-4860-9aa3-fa805d615124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='newData'])[3]</value>
      <webElementGuid>85382445-20c3-4c5a-9638-08f63ac99dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content3']/div/button</value>
      <webElementGuid>6893ec00-f2f5-41b4-8cdd-bce6b13cf40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 20 entries'])[1]/following::button[1]</value>
      <webElementGuid>2cff14db-8277-4060-a4f8-cf295c4df0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absence Scan'])[2]/following::button[3]</value>
      <webElementGuid>ee3f5de7-361c-4043-8677-f43b87323585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Roles'])[3]/preceding::button[1]</value>
      <webElementGuid>5f862407-0f64-4487-a1ac-87520bda4b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/button</value>
      <webElementGuid>2fe3542e-7994-4215-9c76-4046705abb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'newData' and (text() = '  New' or . = '  New')]</value>
      <webElementGuid>2831d9b8-f0e6-4aaf-947f-ca9060320984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
