<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_Add-Menu</name>
   <tag></tag>
   <elementGuidId>e6421702-616c-4d35-bcab-aa24229b344d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formAddMenu > div.modal-content > div.modal-footer > button.btn.btn-primary.btn-roles.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61af36f8-8a8c-49f3-a00d-1a62751cc220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fb55bf62-1c51-4267-b5f0-738fd2ece0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-roles btn-block</value>
      <webElementGuid>568081b6-33bd-4d51-b93b-ac14532a0be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Save
                                </value>
      <webElementGuid>99614fb6-8b61-40c5-b463-b08e9ec7ffe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAddMenu&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-primary btn-roles btn-block&quot;]</value>
      <webElementGuid>68a428ea-c442-46d1-a0dc-20117f311815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[5]</value>
      <webElementGuid>fa54257d-24aa-40f5-bd4c-058b673ae730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddMenu']/div/div[3]/button</value>
      <webElementGuid>3adbd4d6-7c78-4106-9544-c2ac83e074be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Add Mapping Roles'])[2]/following::button[1]</value>
      <webElementGuid>40aa9e21-543b-48a5-be02-c91bce21dac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[4]/following::button[1]</value>
      <webElementGuid>9019250c-43a3-45d1-a94b-19d42f9fe0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Edit Mapping Roles'])[2]/preceding::button[1]</value>
      <webElementGuid>4709b9b2-752b-4d84-8525-087c792fcf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[6]/preceding::button[1]</value>
      <webElementGuid>0282b374-3b48-4f31-b9a3-2bb382f00dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div/div[3]/button</value>
      <webElementGuid>63231180-5492-480c-bcaf-139d1d2c76ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                    Save
                                ' or . = '
                                    Save
                                ')]</value>
      <webElementGuid>54dc830a-281f-4826-bb94-936ef5b4fc3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
