<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_menu-description</name>
   <tag></tag>
   <elementGuidId>f81b7ef0-b6c9-4523-a6c3-094cc60e9bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Menu Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0daac15-daf4-4267-9dfd-e3180a323583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a74828be-77ee-4031-b1ae-d75da9f8b168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>4c7568e0-006b-4700-8d1b-acc496b2ad2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>7b67052f-c033-4de7-8849-e3c1adac97a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>683bd864-90de-4daf-bdaf-76367cdb53b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Menu Description</value>
      <webElementGuid>32188428-13c5-4932-9896-95d4a122e97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f321643c-0af7-4160-a8bc-97f6493cde64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)</value>
      <webElementGuid>16d4d6f6-8529-4daf-8676-fef8dba64f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='menu']</value>
      <webElementGuid>3359b86c-ee39-4a38-a52e-728e7b5d0f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddMenu']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>b04b79fb-ab1c-45f7-8da2-d2880de616bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>9307ce01-6dd6-40fa-8cc3-75018e103076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'menu' and @id = 'menu' and @placeholder = 'Menu Description']</value>
      <webElementGuid>9d02b1c2-fdc5-40ee-b6ec-ecbf270ad3ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
