<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link</name>
   <tag></tag>
   <elementGuidId>233588ce-bfe2-4659-beab-208d6ba15dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Link&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d93e26cd-def3-421e-896e-ff5381318e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f520b59-3fc4-44e8-9d70-53bd1b6b028f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>141d8cb0-7d79-41f9-9690-11209be576e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>f8116507-997d-4f04-8bb8-41a8c3653c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>24e250c4-75a0-4d3a-9981-56bfc8ae3a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>2a00c851-c08a-4f6e-94ac-98a8aff07a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33b80906-1e8f-409b-a3fb-c656219e300b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link&quot;)</value>
      <webElementGuid>66016c87-b6d1-48ae-99fc-56ed3d974550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link']</value>
      <webElementGuid>5a33c5d6-e22a-4a29-a634-a1032b773fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddMenu']/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>eb0586b9-c5d0-4967-b09f-8d07ac270b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>f824c754-f010-4d04-8684-cd8e5d04dfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'link' and @id = 'link' and @placeholder = 'Link']</value>
      <webElementGuid>0c68ec79-8cc9-45e1-9c11-4f6f111b9f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
