<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Icon</name>
   <tag></tag>
   <elementGuidId>f14aa94f-875c-479c-8653-e194d23a2e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20f4cfbf-1365-4921-b819-d1b9b6e62872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c9f8470-02c0-418b-b347-02ab75009889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>3af44c7a-a36f-44dd-af26-a7b13bb6ed7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>feef728a-4730-4b40-bbc9-f39cbfc36c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>5325e111-e429-4976-9482-2c2bda1e46c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Icon</value>
      <webElementGuid>51c84489-77bb-4a57-8475-4f049d6a3f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1c8908dd-c9e7-4008-8ffc-ba2268afd08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon&quot;)</value>
      <webElementGuid>e4f91fff-5fe3-493e-97cb-c7002f8a9788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='icon']</value>
      <webElementGuid>6ce3c673-0cbb-44f3-8c3d-685dee4f0a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddMenu']/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>adab5e96-523d-4804-9b08-5f28e8f51f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>d18c3ae8-fe14-49cc-885a-f0af826a2b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'icon' and @id = 'icon' and @placeholder = 'Icon']</value>
      <webElementGuid>0d023cbf-aabe-4abe-8e8b-e1713aadaceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
