<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sidebar Left Menu</name>
   <tag></tag>
   <elementGuidId>632cfac3-65f0-40ef-b58a-7a9a168fec02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebarToggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sidebarToggle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dc59c5c-e7ad-40b3-9662-9c89e60e9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle border-0</value>
      <webElementGuid>3d9bc452-0451-4aaa-8439-6abfc3b0f4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebarToggle</value>
      <webElementGuid>f7082e8c-74be-48b0-9788-9dcfa6c639bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarToggle&quot;)</value>
      <webElementGuid>96bf49f7-e4a3-4bfe-928a-2d6e9e944bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sidebarToggle']</value>
      <webElementGuid>778a0c65-46ef-458b-9c14-b8cd8e8370aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='accordionSidebar']/div[2]/button</value>
      <webElementGuid>f179d1a8-0585-4dee-adfe-0e2237efc008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>35fa5aa3-0e89-41ab-b9b2-7159cd3c9db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sidebarToggle']</value>
      <webElementGuid>95c3df88-177a-4093-a5df-b98f4ea1713e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
