<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email-edit</name>
   <tag></tag>
   <elementGuidId>c4ebc1d4-c2d9-47fa-af57-38325d2595c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b813efd6-c237-4a45-8c5d-772421675bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>893a3d88-070a-43c9-aedf-134634ec2898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>4108dd9c-f73a-41c0-8d03-52371b697d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e2669cdb-fae7-430f-b36f-4d0ff8869c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_edit</value>
      <webElementGuid>b4fe4b19-d372-4ba9-ab2b-ce033bfc6415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>1256634f-a3c7-4f3e-8297-23b686d03f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_edit&quot;)</value>
      <webElementGuid>3d1b3fa4-703c-4061-be2b-0b8b2c1b57f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_edit']</value>
      <webElementGuid>817e8a09-eec4-4482-a4b9-fa2ed00fc62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditInvitation']/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>185b8738-48a8-4162-92de-3350ac51ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>1b355862-e593-4b8a-9b36-edd9dd7c5fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'email_edit' and @placeholder = 'Email Address']</value>
      <webElementGuid>d4bf8d8a-ac7b-4850-acbe-422e63de87fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
