<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Action_viewBarcode-Manto</name>
   <tag></tag>
   <elementGuidId>8edca57c-13ea-4037-b111-fca5e60110c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.viewBarcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dtRegister']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;[View]&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>779a3bf8-c8ec-4dfd-8374-91985af26c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>86d8e975-eceb-4960-973a-8c66d29634b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>viewBarcode</value>
      <webElementGuid>8c85b4b9-5701-4f34-aa07-d732a0a9296f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-barcode_token</name>
      <type>Main</type>
      <value>95499631-8712-4f5b-b23b-ff9803955549</value>
      <webElementGuid>dfa60a68-3b44-4cac-a4dd-e4e4c0a05948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[View]</value>
      <webElementGuid>ac3a14c2-f2db-47c2-be14-8ba0464f0606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtRegister&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[@class=&quot;viewBarcode&quot;]</value>
      <webElementGuid>df6155c0-5699-4870-8e58-50445915372e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtRegister']/tbody/tr/td[2]/a</value>
      <webElementGuid>729b12af-704a-497e-a46b-f343eca7a216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'[View]')]</value>
      <webElementGuid>067b2302-5d05-4e74-9ee2-9ee0a3396cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[1]</value>
      <webElementGuid>91854bbb-f696-4027-976b-d1ffe1eef4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[2]/following::a[1]</value>
      <webElementGuid>08432bcc-e57d-434d-86b4-6829f3728b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANTOundefinedMMSGI'])[1]/preceding::a[1]</value>
      <webElementGuid>06ec1860-4ee8-4ea0-b612-bf7efc13438a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manto.manto@mmsgroup.co.id'])[1]/preceding::a[1]</value>
      <webElementGuid>0de75e4d-8c7a-434d-99bd-dbad96fdcbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[View]']/parent::*</value>
      <webElementGuid>cf704360-d378-46c7-9732-2de7c226f9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>9e301e54-16c4-4f1d-995a-66c318b7f28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>27f4fc64-acaa-4722-bcab-710dd1260cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '[View]' or . = '[View]')]</value>
      <webElementGuid>24c01bcc-5162-4dc2-800f-4589937a3cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
