<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Confirm_viewBarcode_10203073</name>
   <tag></tag>
   <elementGuidId>fec6ca8a-1634-49b1-8c0b-1ab1f91d598e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.viewBarcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dtRegister']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;[View]&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2786f961-343d-4e53-bac2-71f59bab135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9af73491-baf9-409d-b4b3-4fd805bd116b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>viewBarcode</value>
      <webElementGuid>f951b82a-2a3b-4936-85f5-20004a73a3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-barcode_token</name>
      <type>Main</type>
      <value>3a24ba93-6a86-44a4-ab52-9ecaeb1162da</value>
      <webElementGuid>cdbb4026-e821-4e44-a4b1-4811ead5ce7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[View]</value>
      <webElementGuid>f9e736e6-ce62-4610-aef0-3643b338849c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtRegister&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[@class=&quot;viewBarcode&quot;]</value>
      <webElementGuid>1e893595-f74a-483e-a28b-a4a355a3aec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtRegister']/tbody/tr/td[2]/a</value>
      <webElementGuid>bb915413-e7c9-44d4-9bdd-5707fd9d4a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'[View]')]</value>
      <webElementGuid>cda88478-43da-4ca9-a765-0d803c5f7a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[2]/following::a[1]</value>
      <webElementGuid>55da45b8-e606-44de-9d79-0a2fe692b2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WA'])[2]/following::a[1]</value>
      <webElementGuid>0acfb038-2524-41d3-a9a0-1624aeb6763a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANTO10203073PT MMS Group Indonesia'])[1]/preceding::a[1]</value>
      <webElementGuid>d8328ee0-116d-44c3-a487-1f443db6c91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manto.manto@mmsgroup.co.id'])[1]/preceding::a[1]</value>
      <webElementGuid>f2971425-c1df-4811-b2dd-c86f50040aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[View]']/parent::*</value>
      <webElementGuid>76492ee0-d070-4517-b1a2-f8bfd7e207fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>1263439d-6a63-4e10-b8a6-d03b4205be92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>d4bca526-f125-414c-9647-de23a5e6924c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '[View]' or . = '[View]')]</value>
      <webElementGuid>10b83509-a0ba-4319-aef3-f2d452ab0a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
