<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Showing_Back</name>
   <tag></tag>
   <elementGuidId>ebc5c8ed-629f-4896-bf88-c66bec720c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtRegister_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dtRegister_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dtRegister_previous</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>09a57cf9-7e2a-476a-bae8-807a0b585f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>533d753c-bf05-4782-9751-094d20907447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtRegister_previous</value>
      <webElementGuid>6a30ab8b-e014-4322-b347-3b5480a9399e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>33957b77-a47f-4e17-bb89-989bb6d9e5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtRegister_previous&quot;)</value>
      <webElementGuid>3bf8331e-077a-475f-82b0-5034f3dcd727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dtRegister_previous']</value>
      <webElementGuid>72a937f1-f954-4766-9c40-001a2546e8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dtRegister_paginate']/ul/li</value>
      <webElementGuid>c618d700-0bd4-4a25-991f-9b1d6ffb1a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 88 entries'])[1]/following::li[1]</value>
      <webElementGuid>8e77a930-78db-48a4-ace0-ed7b15d45169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Late Check In'])[10]/following::li[1]</value>
      <webElementGuid>81bdd358-9f56-46e1-936b-378eabf65ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © galadinner.mmsgroup.co.id 2023'])[1]/preceding::li[9]</value>
      <webElementGuid>a2caae37-4a46-4cb6-ac38-499db76367e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li</value>
      <webElementGuid>7006e44b-b722-436b-a25d-617e9e8eb138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dtRegister_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>c97a7eea-4d67-4094-916c-d97b87fb48bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
